apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: grafana-mysql
  name: grafana-mysql
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-mysql
  template:
    metadata:
      labels:
        app: grafana-mysql
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: grafana
        image: mysql:5.5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-mysql
  name: grafana-mysql
  namespace: kube-system
spec:
  ports:
  - name: http-3306
    port: 3306
    targetPort: 3306
  selector:
    app: grafana-mysql
  type: NodePort
